package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "servicingportaldb")
public class Image implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer imageId;
	private ImageCategory imagecategory;
	private PartnerAccount partneraccount;
	private String imageName;
	private String imageHref;
	private Date imageUploadDate;

	public Image() {
	}

	public Image(ImageCategory imagecategory, PartnerAccount partneraccount, String imageName, String imageHref,
			Date imageUploadDate) {
		this.imagecategory = imagecategory;
		this.partneraccount = partneraccount;
		this.imageName = imageName;
		this.imageHref = imageHref;
		this.imageUploadDate = imageUploadDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ImageID", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ImgCatID", nullable = false)
	public ImageCategory getImagecategory() {
		return this.imagecategory;
	}

	public void setImagecategory(ImageCategory imagecategory) {
		this.imagecategory = imagecategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UploadBy", nullable = false)
	public PartnerAccount getPartneraccount() {
		return this.partneraccount;
	}

	public void setPartneraccount(PartnerAccount partneraccount) {
		this.partneraccount = partneraccount;
	}

	@Column(name = "ImageName", nullable = false, length = 100)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "ImageHref", nullable = false, length = 100)
	public String getImageHref() {
		return this.imageHref;
	}

	public void setImageHref(String imageHref) {
		this.imageHref = imageHref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ImageUploadDate", nullable = false, length = 19)
	public Date getImageUploadDate() {
		return this.imageUploadDate;
	}

	public void setImageUploadDate(Date imageUploadDate) {
		this.imageUploadDate = imageUploadDate;
	}

}
