package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Qnacatelogy generated by hbm2java
 */
@Entity
@Table(name = "qnacatelogy", catalog = "servicingportaldb")
public class QnACatelogy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer qnAcatId;
	private QnACatelogy qnacatelogy;
	private String qnAcatName;
	private Date createDate;
	private Date modifyDate;
	private Set<QnACatelogy> qnacatelogies = new HashSet<QnACatelogy>(0);
	private Set<QnA> qnas = new HashSet<QnA>(0);

	public QnACatelogy() {
	}

	public QnACatelogy(String qnAcatName, Date createDate, Date modifyDate) {
		this.qnAcatName = qnAcatName;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public QnACatelogy(QnACatelogy qnacatelogy, String qnAcatName, Date createDate, Date modifyDate,
			Set<QnACatelogy> qnacatelogies, Set<QnA> qnas) {
		this.qnacatelogy = qnacatelogy;
		this.qnAcatName = qnAcatName;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.qnacatelogies = qnacatelogies;
		this.qnas = qnas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QnACatID", unique = true, nullable = false)
	public Integer getQnAcatId() {
		return this.qnAcatId;
	}

	public void setQnAcatId(Integer qnAcatId) {
		this.qnAcatId = qnAcatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PQnACatID")
	public QnACatelogy getQnacatelogy() {
		return this.qnacatelogy;
	}

	public void setQnacatelogy(QnACatelogy qnacatelogy) {
		this.qnacatelogy = qnacatelogy;
	}

	@Column(name = "QnACatName", nullable = false, length = 100)
	public String getQnAcatName() {
		return this.qnAcatName;
	}

	public void setQnAcatName(String qnAcatName) {
		this.qnAcatName = qnAcatName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qnacatelogy")
	public Set<QnACatelogy> getQnacatelogies() {
		return this.qnacatelogies;
	}

	public void setQnacatelogies(Set<QnACatelogy> qnacatelogies) {
		this.qnacatelogies = qnacatelogies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qnacatelogy")
	public Set<QnA> getQnas() {
		return this.qnas;
	}

	public void setQnas(Set<QnA> qnas) {
		this.qnas = qnas;
	}

}
