package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customeraccount generated by hbm2java
 */
@Entity
@Table(name = "customeraccount", catalog = "servicingportaldb")
public class CustomerAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String customerEmail;
	private String customerPassword;
	private String customerFullName;
	private Date customerDob;
	private String customerImage;
	private String customerAddress;
	private String customerPhone;
	private String customerIdentityNumber;
	private String customerBankAccount;
	private Date createDate;
	private Date modifyDate;
	private Set<OrderService> orderservices = new HashSet<OrderService>(0);

	public CustomerAccount() {
	}

	public CustomerAccount(String customerEmail, String customerPassword, String customerFullName,
			String customerIdentityNumber) {
		this.customerEmail = customerEmail;
		this.customerPassword = customerPassword;
		this.customerFullName = customerFullName;
		this.customerIdentityNumber = customerIdentityNumber;
	}

	public CustomerAccount(String customerEmail, String customerPassword, String customerFullName, Date customerDob,
			String customerImage, String customerAddress, String customerPhone, String customerIdentityNumber,
			String customerBankAccount, Date createDate, Date modifyDate, Set<OrderService> orderservices) {
		this.customerEmail = customerEmail;
		this.customerPassword = customerPassword;
		this.customerFullName = customerFullName;
		this.customerDob = customerDob;
		this.customerImage = customerImage;
		this.customerAddress = customerAddress;
		this.customerPhone = customerPhone;
		this.customerIdentityNumber = customerIdentityNumber;
		this.customerBankAccount = customerBankAccount;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.orderservices = orderservices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CustomerID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CustomerEmail", nullable = false, length = 100)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "CustomerPassword", nullable = false, length = 100)
	public String getCustomerPassword() {
		return this.customerPassword;
	}

	public void setCustomerPassword(String customerPassword) {
		this.customerPassword = customerPassword;
	}

	@Column(name = "CustomerFullName", nullable = false, length = 100)
	public String getCustomerFullName() {
		return this.customerFullName;
	}

	public void setCustomerFullName(String customerFullName) {
		this.customerFullName = customerFullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CustomerDOB", length = 10)
	public Date getCustomerDob() {
		return this.customerDob;
	}

	public void setCustomerDob(Date customerDob) {
		this.customerDob = customerDob;
	}

	@Column(name = "CustomerImage", length = 200)
	public String getCustomerImage() {
		return this.customerImage;
	}

	public void setCustomerImage(String customerImage) {
		this.customerImage = customerImage;
	}

	@Column(name = "CustomerAddress", length = 200)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "CustomerPhone", length = 20)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "CustomerIdentityNumber", nullable = false, length = 20)
	public String getCustomerIdentityNumber() {
		return this.customerIdentityNumber;
	}

	public void setCustomerIdentityNumber(String customerIdentityNumber) {
		this.customerIdentityNumber = customerIdentityNumber;
	}

	@Column(name = "CustomerBankAccount", length = 20)
	public String getCustomerBankAccount() {
		return this.customerBankAccount;
	}

	public void setCustomerBankAccount(String customerBankAccount) {
		this.customerBankAccount = customerBankAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customeraccount")
	public Set<OrderService> getOrderservices() {
		return this.orderservices;
	}

	public void setOrderservices(Set<OrderService> orderservices) {
		this.orderservices = orderservices;
	}

}
