package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailservice generated by hbm2java
 */
@Entity
@Table(name = "detailservice", catalog = "servicingportaldb")
public class DetailService implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer detailServiceId;
	private EmployeeAccount employeeaccount;
	private FieldService fieldservice;
	private TypeService typeservice;
	private String detailServiceName;
	private String detailServiceDescription;
	private Date createDate;
	private Set<ServicePostDetail> servicepostdetails = new HashSet<ServicePostDetail>(0);

	public DetailService() {
	}

	public DetailService(EmployeeAccount employeeaccount, FieldService fieldservice, TypeService typeservice,
			String detailServiceName, Date createDate) {
		this.employeeaccount = employeeaccount;
		this.fieldservice = fieldservice;
		this.typeservice = typeservice;
		this.detailServiceName = detailServiceName;
		this.createDate = createDate;
	}

	public DetailService(EmployeeAccount employeeaccount, FieldService fieldservice, TypeService typeservice,
			String detailServiceName, String detailServiceDescription, Date createDate,
			Set<ServicePostDetail> servicepostdetails) {
		this.employeeaccount = employeeaccount;
		this.fieldservice = fieldservice;
		this.typeservice = typeservice;
		this.detailServiceName = detailServiceName;
		this.detailServiceDescription = detailServiceDescription;
		this.createDate = createDate;
		this.servicepostdetails = servicepostdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DetailServiceID", unique = true, nullable = false)
	public Integer getDetailServiceId() {
		return this.detailServiceId;
	}

	public void setDetailServiceId(Integer detailServiceId) {
		this.detailServiceId = detailServiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateBy", nullable = false)
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FServiceID", nullable = false)
	public FieldService getFieldservice() {
		return this.fieldservice;
	}

	public void setFieldservice(FieldService fieldservice) {
		this.fieldservice = fieldservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeServiceID", nullable = false)
	public TypeService getTypeservice() {
		return this.typeservice;
	}

	public void setTypeservice(TypeService typeservice) {
		this.typeservice = typeservice;
	}

	@Column(name = "DetailServiceName", nullable = false, length = 100)
	public String getDetailServiceName() {
		return this.detailServiceName;
	}

	public void setDetailServiceName(String detailServiceName) {
		this.detailServiceName = detailServiceName;
	}

	@Column(name = "DetailServiceDescription", length = 500)
	public String getDetailServiceDescription() {
		return this.detailServiceDescription;
	}

	public void setDetailServiceDescription(String detailServiceDescription) {
		this.detailServiceDescription = detailServiceDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailservice")
	public Set<ServicePostDetail> getServicepostdetails() {
		return this.servicepostdetails;
	}

	public void setServicepostdetails(Set<ServicePostDetail> servicepostdetails) {
		this.servicepostdetails = servicepostdetails;
	}

}
