package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Scheduledate generated by hbm2java
 */
@Entity
@Table(name = "scheduledate", catalog = "servicingportaldb")
public class ScheduleDate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer scheDateId;
	private ScheduleManage schedulemanage;
	private int scheDateDate;
	private String scheDateName;
	private Date createDate;
	private Date modifyDate;
	private Set<DetailScheduleDate> detailscheduledates = new HashSet<DetailScheduleDate>(0);

	public ScheduleDate() {
	}

	public ScheduleDate(ScheduleManage schedulemanage, int scheDateDate, String scheDateName, Date createDate,
			Date modifyDate) {
		this.schedulemanage = schedulemanage;
		this.scheDateDate = scheDateDate;
		this.scheDateName = scheDateName;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public ScheduleDate(ScheduleManage schedulemanage, int scheDateDate, String scheDateName, Date createDate,
			Date modifyDate, Set<DetailScheduleDate> detailscheduledates) {
		this.schedulemanage = schedulemanage;
		this.scheDateDate = scheDateDate;
		this.scheDateName = scheDateName;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.detailscheduledates = detailscheduledates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ScheDateID", unique = true, nullable = false)
	public Integer getScheDateId() {
		return this.scheDateId;
	}

	public void setScheDateId(Integer scheDateId) {
		this.scheDateId = scheDateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ScheduleManageID", nullable = false)
	public ScheduleManage getSchedulemanage() {
		return this.schedulemanage;
	}

	public void setSchedulemanage(ScheduleManage schedulemanage) {
		this.schedulemanage = schedulemanage;
	}

	@Column(name = "ScheDateDate", nullable = false)
	public int getScheDateDate() {
		return this.scheDateDate;
	}

	public void setScheDateDate(int scheDateDate) {
		this.scheDateDate = scheDateDate;
	}

	@Column(name = "ScheDateName", nullable = false, length = 100)
	public String getScheDateName() {
		return this.scheDateName;
	}

	public void setScheDateName(String scheDateName) {
		this.scheDateName = scheDateName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduledate")
	public Set<DetailScheduleDate> getDetailscheduledates() {
		return this.detailscheduledates;
	}

	public void setDetailscheduledates(Set<DetailScheduleDate> detailscheduledates) {
		this.detailscheduledates = detailscheduledates;
	}

}
