package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailorder generated by hbm2java
 */
@Entity
@Table(name = "detailorder", catalog = "servicingportaldb")
public class DetailOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer detailOrderId;
	private OrderService orderservice;
	private ServicePostDetail servicepostdetail;
	private Date usingDate;
	private Integer quantity;
	private String note;
	private Integer price;

	public DetailOrder() {
	}

	public DetailOrder(OrderService orderservice, ServicePostDetail servicepostdetail, Date usingDate, Integer quantity,
			String note, Integer price) {
		this.orderservice = orderservice;
		this.servicepostdetail = servicepostdetail;
		this.usingDate = usingDate;
		this.quantity = quantity;
		this.note = note;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DetailOrderID", unique = true, nullable = false)
	public Integer getDetailOrderId() {
		return this.detailOrderId;
	}

	public void setDetailOrderId(Integer detailOrderId) {
		this.detailOrderId = detailOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderID")
	public OrderService getOrderservice() {
		return this.orderservice;
	}

	public void setOrderservice(OrderService orderservice) {
		this.orderservice = orderservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DetailServicePostID")
	public ServicePostDetail getServicepostdetail() {
		return this.servicepostdetail;
	}

	public void setServicepostdetail(ServicePostDetail servicepostdetail) {
		this.servicepostdetail = servicepostdetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UsingDate", length = 19)
	public Date getUsingDate() {
		return this.usingDate;
	}

	public void setUsingDate(Date usingDate) {
		this.usingDate = usingDate;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "Price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
