package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Webdatacontent generated by hbm2java
 */
@Entity
@Table(name = "webdatacontent", catalog = "servicingportaldb")
public class WebDataContent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer wdcid;
	private EmployeeAccount employeeaccount;
	private String wdcname;
	private String wdccontent;
	private String wdcimage;
	private Date createDate;
	private Date modifyDate;

	public WebDataContent() {
	}

	public WebDataContent(EmployeeAccount employeeaccount, String wdcname, String wdccontent, Date createDate,
			Date modifyDate) {
		this.employeeaccount = employeeaccount;
		this.wdcname = wdcname;
		this.wdccontent = wdccontent;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public WebDataContent(EmployeeAccount employeeaccount, String wdcname, String wdccontent, String wdcimage,
			Date createDate, Date modifyDate) {
		this.employeeaccount = employeeaccount;
		this.wdcname = wdcname;
		this.wdccontent = wdccontent;
		this.wdcimage = wdcimage;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "WDCID", unique = true, nullable = false)
	public Integer getWdcid() {
		return this.wdcid;
	}

	public void setWdcid(Integer wdcid) {
		this.wdcid = wdcid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateUpdateBy", nullable = false)
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@Column(name = "WDCName", nullable = false, length = 100)
	public String getWdcname() {
		return this.wdcname;
	}

	public void setWdcname(String wdcname) {
		this.wdcname = wdcname;
	}

	@Column(name = "WDCContent", nullable = false, length = 500)
	public String getWdccontent() {
		return this.wdccontent;
	}

	public void setWdccontent(String wdccontent) {
		this.wdccontent = wdccontent;
	}

	@Column(name = "WDCImage", length = 100)
	public String getWdcimage() {
		return this.wdcimage;
	}

	public void setWdcimage(String wdcimage) {
		this.wdcimage = wdcimage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
