package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicepostdetail generated by hbm2java
 */
@Entity
@Table(name = "servicepostdetail", catalog = "servicingportaldb")
public class ServicePostDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer spdid;
	private DetailService detailservice;
	private EmployeeAccount employeeaccount;
	private ServicePost servicepost;
	private boolean isAccept;
	private int spdprice;
	private boolean isModify;
	private Date createDate;
	private Date modifyDate;
	private int spdpriceNew;
	private Set<DetailOrder> detailorders = new HashSet<DetailOrder>(0);

	public ServicePostDetail() {
	}

	public ServicePostDetail(DetailService detailservice, ServicePost servicepost, boolean isAccept, int spdprice,
			boolean isModify, Date createDate, Date modifyDate, int spdpriceNew) {
		this.detailservice = detailservice;
		this.servicepost = servicepost;
		this.isAccept = isAccept;
		this.spdprice = spdprice;
		this.isModify = isModify;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.spdpriceNew = spdpriceNew;
	}

	public ServicePostDetail(DetailService detailservice, EmployeeAccount employeeaccount, ServicePost servicepost,
			boolean isAccept, int spdprice, boolean isModify, Date createDate, Date modifyDate, int spdpriceNew,
			Set<DetailOrder> detailorders) {
		this.detailservice = detailservice;
		this.employeeaccount = employeeaccount;
		this.servicepost = servicepost;
		this.isAccept = isAccept;
		this.spdprice = spdprice;
		this.isModify = isModify;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.spdpriceNew = spdpriceNew;
		this.detailorders = detailorders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SPDID", unique = true, nullable = false)
	public Integer getSpdid() {
		return this.spdid;
	}

	public void setSpdid(Integer spdid) {
		this.spdid = spdid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DetailServiceID", nullable = false)
	public DetailService getDetailservice() {
		return this.detailservice;
	}

	public void setDetailservice(DetailService detailservice) {
		this.detailservice = detailservice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AcceptBy")
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ServicePostID", nullable = false)
	public ServicePost getServicepost() {
		return this.servicepost;
	}

	public void setServicepost(ServicePost servicepost) {
		this.servicepost = servicepost;
	}

	@Column(name = "IsAccept", nullable = false)
	public boolean isIsAccept() {
		return this.isAccept;
	}

	public void setIsAccept(boolean isAccept) {
		this.isAccept = isAccept;
	}

	@Column(name = "SPDPrice", nullable = false)
	public int getSpdprice() {
		return this.spdprice;
	}

	public void setSpdprice(int spdprice) {
		this.spdprice = spdprice;
	}

	@Column(name = "IsModify", nullable = false)
	public boolean isIsModify() {
		return this.isModify;
	}

	public void setIsModify(boolean isModify) {
		this.isModify = isModify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "SPDPriceNew", nullable = false)
	public int getSpdpriceNew() {
		return this.spdpriceNew;
	}

	public void setSpdpriceNew(int spdpriceNew) {
		this.spdpriceNew = spdpriceNew;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicepostdetail")
	public Set<DetailOrder> getDetailorders() {
		return this.detailorders;
	}

	public void setDetailorders(Set<DetailOrder> detailorders) {
		this.detailorders = detailorders;
	}

}
