package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "servicingportaldb")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer areaId;
	private City city;
	private String areaName;
	private Set<WorkingArea> workingareas = new HashSet<WorkingArea>(0);

	public Area() {
	}

	public Area(City city, String areaName) {
		this.city = city;
		this.areaName = areaName;
	}

	public Area(City city, String areaName, Set<WorkingArea> workingareas) {
		this.city = city;
		this.areaName = areaName;
		this.workingareas = workingareas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AreaID", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CityID", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "AreaName", nullable = false, length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<WorkingArea> getWorkingareas() {
		return this.workingareas;
	}

	public void setWorkingareas(Set<WorkingArea> workingareas) {
		this.workingareas = workingareas;
	}

}
