package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "servicingportaldb")
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cmtId;
	private Comment comment;
	private ServicePost servicepost;
	private String cusName;
	private String cusEmail;
	private String cusPhone;
	private String content;
	private Date createDate;
	private boolean isNeedRate;
	private byte[] ratePoint;
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Comment() {
	}

	public Comment(ServicePost servicepost, String cusName, String content, Date createDate, boolean isNeedRate) {
		this.servicepost = servicepost;
		this.cusName = cusName;
		this.content = content;
		this.createDate = createDate;
		this.isNeedRate = isNeedRate;
	}

	public Comment(Comment comment, ServicePost servicepost, String cusName, String cusEmail, String cusPhone,
			String content, Date createDate, boolean isNeedRate, byte[] ratePoint, Set<Comment> comments) {
		this.comment = comment;
		this.servicepost = servicepost;
		this.cusName = cusName;
		this.cusEmail = cusEmail;
		this.cusPhone = cusPhone;
		this.content = content;
		this.createDate = createDate;
		this.isNeedRate = isNeedRate;
		this.ratePoint = ratePoint;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CmtID", unique = true, nullable = false)
	public Integer getCmtId() {
		return this.cmtId;
	}

	public void setCmtId(Integer cmtId) {
		this.cmtId = cmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PCmtID")
	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ServicePostID", nullable = false)
	public ServicePost getServicepost() {
		return this.servicepost;
	}

	public void setServicepost(ServicePost servicepost) {
		this.servicepost = servicepost;
	}

	@Column(name = "CusName", nullable = false, length = 100)
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "CusEmail", length = 100)
	public String getCusEmail() {
		return this.cusEmail;
	}

	public void setCusEmail(String cusEmail) {
		this.cusEmail = cusEmail;
	}

	@Column(name = "CusPhone", length = 100)
	public String getCusPhone() {
		return this.cusPhone;
	}

	public void setCusPhone(String cusPhone) {
		this.cusPhone = cusPhone;
	}

	@Column(name = "Content", nullable = false, length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "IsNeedRate", nullable = false)
	public boolean isIsNeedRate() {
		return this.isNeedRate;
	}

	public void setIsNeedRate(boolean isNeedRate) {
		this.isNeedRate = isNeedRate;
	}

	@Column(name = "RatePoint")
	public byte[] getRatePoint() {
		return this.ratePoint;
	}

	public void setRatePoint(byte[] ratePoint) {
		this.ratePoint = ratePoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comment")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
