package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fieldservice generated by hbm2java
 */
@Entity
@Table(name = "fieldservice", catalog = "servicingportaldb")
public class FieldService implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer fserviceId;
	private EmployeeAccount employeeaccount;
	private FieldService fieldservice;
	private String fserviceName;
	private String fserviceDescription;
	private String fserviceImage;
	private String fserviceHref;
	private Date createDate;
	private Set<FieldService> fieldservices = new HashSet<FieldService>(0);
	private Set<DetailService> detailservices = new HashSet<DetailService>(0);
	private Set<EmployeeManageFservice> employeemanagefservices = new HashSet<EmployeeManageFservice>(0);
	private Set<ServicePost> serviceposts = new HashSet<ServicePost>(0);

	public FieldService() {
	}

	public FieldService(EmployeeAccount employeeaccount, String fserviceName, String fserviceImage, String fserviceHref,
			Date createDate) {
		this.employeeaccount = employeeaccount;
		this.fserviceName = fserviceName;
		this.fserviceImage = fserviceImage;
		this.fserviceHref = fserviceHref;
		this.createDate = createDate;
	}

	public FieldService(EmployeeAccount employeeaccount, FieldService fieldservice, String fserviceName,
			String fserviceDescription, String fserviceImage, String fserviceHref, Date createDate,
			Set<FieldService> fieldservices, Set<DetailService> detailservices,
			Set<EmployeeManageFservice> employeemanagefservices, Set<ServicePost> serviceposts) {
		this.employeeaccount = employeeaccount;
		this.fieldservice = fieldservice;
		this.fserviceName = fserviceName;
		this.fserviceDescription = fserviceDescription;
		this.fserviceImage = fserviceImage;
		this.fserviceHref = fserviceHref;
		this.createDate = createDate;
		this.fieldservices = fieldservices;
		this.detailservices = detailservices;
		this.employeemanagefservices = employeemanagefservices;
		this.serviceposts = serviceposts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FServiceID", unique = true, nullable = false)
	public Integer getFserviceId() {
		return this.fserviceId;
	}

	public void setFserviceId(Integer fserviceId) {
		this.fserviceId = fserviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateBy", nullable = false)
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PFServiceID")
	public FieldService getFieldservice() {
		return this.fieldservice;
	}

	public void setFieldservice(FieldService fieldservice) {
		this.fieldservice = fieldservice;
	}

	@Column(name = "FServiceName", nullable = false, length = 100)
	public String getFserviceName() {
		return this.fserviceName;
	}

	public void setFserviceName(String fserviceName) {
		this.fserviceName = fserviceName;
	}

	@Column(name = "FServiceDescription", length = 500)
	public String getFserviceDescription() {
		return this.fserviceDescription;
	}

	public void setFserviceDescription(String fserviceDescription) {
		this.fserviceDescription = fserviceDescription;
	}

	@Column(name = "FServiceImage", nullable = false, length = 100)
	public String getFserviceImage() {
		return this.fserviceImage;
	}

	public void setFserviceImage(String fserviceImage) {
		this.fserviceImage = fserviceImage;
	}

	@Column(name = "FServiceHref", nullable = false, length = 100)
	public String getFserviceHref() {
		return this.fserviceHref;
	}

	public void setFserviceHref(String fserviceHref) {
		this.fserviceHref = fserviceHref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldservice")
	public Set<FieldService> getFieldservices() {
		return this.fieldservices;
	}

	public void setFieldservices(Set<FieldService> fieldservices) {
		this.fieldservices = fieldservices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldservice")
	public Set<DetailService> getDetailservices() {
		return this.detailservices;
	}

	public void setDetailservices(Set<DetailService> detailservices) {
		this.detailservices = detailservices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldservice")
	public Set<EmployeeManageFservice> getEmployeemanagefservices() {
		return this.employeemanagefservices;
	}

	public void setEmployeemanagefservices(Set<EmployeeManageFservice> employeemanagefservices) {
		this.employeemanagefservices = employeemanagefservices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fieldservice")
	public Set<ServicePost> getServiceposts() {
		return this.serviceposts;
	}

	public void setServiceposts(Set<ServicePost> serviceposts) {
		this.serviceposts = serviceposts;
	}

}
