package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partneraccount generated by hbm2java
 */
@Entity
@Table(name = "partneraccount", catalog = "servicingportaldb")
public class PartnerAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer partnerId;
	private EmployeeAccount employeeaccount;
	private String partnerEmail;
	private String partnerPassword;
	private String partnerFullName;
	private String partnerName;
	private String partnerIdentityNumber;
	private String partnerPhone;
	private String partnerAddress;
	private Date partnerDob;
	private String partnerImage;
	private String partnerBankAccount;
	private int partnerType;
	private boolean isAccept;
	private Date createDate;
	private boolean isModify;
	private Date modifyDate;
	private Set<WorkingArea> workingareas = new HashSet<WorkingArea>(0);
	private Set<ServicePost> serviceposts = new HashSet<ServicePost>(0);
	private Set<ImageCategory> imagecategories = new HashSet<ImageCategory>(0);
	private Set<ScheduleManage> schedulemanages = new HashSet<ScheduleManage>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public PartnerAccount() {
	}

	public PartnerAccount(String partnerEmail, String partnerPassword, String partnerFullName, String partnerPhone,
			String partnerAddress, String partnerBankAccount, int partnerType, boolean isAccept, Date createDate,
			boolean isModify, Date modifyDate) {
		this.partnerEmail = partnerEmail;
		this.partnerPassword = partnerPassword;
		this.partnerFullName = partnerFullName;
		this.partnerPhone = partnerPhone;
		this.partnerAddress = partnerAddress;
		this.partnerBankAccount = partnerBankAccount;
		this.partnerType = partnerType;
		this.isAccept = isAccept;
		this.createDate = createDate;
		this.isModify = isModify;
		this.modifyDate = modifyDate;
	}

	public PartnerAccount(EmployeeAccount employeeaccount, String partnerEmail, String partnerPassword,
			String partnerFullName, String partnerName, String partnerIdentityNumber, String partnerPhone,
			String partnerAddress, Date partnerDob, String partnerImage, String partnerBankAccount, int partnerType,
			boolean isAccept, Date createDate, boolean isModify, Date modifyDate, Set<WorkingArea> workingareas,
			Set<ServicePost> serviceposts, Set<ImageCategory> imagecategories, Set<ScheduleManage> schedulemanages,
			Set<Image> images) {
		this.employeeaccount = employeeaccount;
		this.partnerEmail = partnerEmail;
		this.partnerPassword = partnerPassword;
		this.partnerFullName = partnerFullName;
		this.partnerName = partnerName;
		this.partnerIdentityNumber = partnerIdentityNumber;
		this.partnerPhone = partnerPhone;
		this.partnerAddress = partnerAddress;
		this.partnerDob = partnerDob;
		this.partnerImage = partnerImage;
		this.partnerBankAccount = partnerBankAccount;
		this.partnerType = partnerType;
		this.isAccept = isAccept;
		this.createDate = createDate;
		this.isModify = isModify;
		this.modifyDate = modifyDate;
		this.workingareas = workingareas;
		this.serviceposts = serviceposts;
		this.imagecategories = imagecategories;
		this.schedulemanages = schedulemanages;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PartnerID", unique = true, nullable = false)
	public Integer getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AcceptBy")
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@Column(name = "PartnerEmail", nullable = false, length = 100)
	public String getPartnerEmail() {
		return this.partnerEmail;
	}

	public void setPartnerEmail(String partnerEmail) {
		this.partnerEmail = partnerEmail;
	}

	@Column(name = "PartnerPassword", nullable = false, length = 100)
	public String getPartnerPassword() {
		return this.partnerPassword;
	}

	public void setPartnerPassword(String partnerPassword) {
		this.partnerPassword = partnerPassword;
	}

	@Column(name = "PartnerFullName", nullable = false, length = 100)
	public String getPartnerFullName() {
		return this.partnerFullName;
	}

	public void setPartnerFullName(String partnerFullName) {
		this.partnerFullName = partnerFullName;
	}

	@Column(name = "PartnerName", length = 200)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "PartnerIdentityNumber", length = 20)
	public String getPartnerIdentityNumber() {
		return this.partnerIdentityNumber;
	}

	public void setPartnerIdentityNumber(String partnerIdentityNumber) {
		this.partnerIdentityNumber = partnerIdentityNumber;
	}

	@Column(name = "PartnerPhone", nullable = false, length = 20)
	public String getPartnerPhone() {
		return this.partnerPhone;
	}

	public void setPartnerPhone(String partnerPhone) {
		this.partnerPhone = partnerPhone;
	}

	@Column(name = "PartnerAddress", nullable = false, length = 200)
	public String getPartnerAddress() {
		return this.partnerAddress;
	}

	public void setPartnerAddress(String partnerAddress) {
		this.partnerAddress = partnerAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PartnerDOB", length = 10)
	public Date getPartnerDob() {
		return this.partnerDob;
	}

	public void setPartnerDob(Date partnerDob) {
		this.partnerDob = partnerDob;
	}

	@Column(name = "PartnerImage", length = 200)
	public String getPartnerImage() {
		return this.partnerImage;
	}

	public void setPartnerImage(String partnerImage) {
		this.partnerImage = partnerImage;
	}

	@Column(name = "PartnerBankAccount", nullable = false, length = 20)
	public String getPartnerBankAccount() {
		return this.partnerBankAccount;
	}

	public void setPartnerBankAccount(String partnerBankAccount) {
		this.partnerBankAccount = partnerBankAccount;
	}

	@Column(name = "PartnerType", nullable = false)
	public int getPartnerType() {
		return this.partnerType;
	}

	public void setPartnerType(int partnerType) {
		this.partnerType = partnerType;
	}

	@Column(name = "IsAccept", nullable = false)
	public boolean isIsAccept() {
		return this.isAccept;
	}

	public void setIsAccept(boolean isAccept) {
		this.isAccept = isAccept;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "IsModify", nullable = false)
	public boolean isIsModify() {
		return this.isModify;
	}

	public void setIsModify(boolean isModify) {
		this.isModify = isModify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partneraccount")
	public Set<WorkingArea> getWorkingareas() {
		return this.workingareas;
	}

	public void setWorkingareas(Set<WorkingArea> workingareas) {
		this.workingareas = workingareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partneraccount")
	public Set<ServicePost> getServiceposts() {
		return this.serviceposts;
	}

	public void setServiceposts(Set<ServicePost> serviceposts) {
		this.serviceposts = serviceposts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partneraccount")
	public Set<ImageCategory> getImagecategories() {
		return this.imagecategories;
	}

	public void setImagecategories(Set<ImageCategory> imagecategories) {
		this.imagecategories = imagecategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partneraccount")
	public Set<ScheduleManage> getSchedulemanages() {
		return this.schedulemanages;
	}

	public void setSchedulemanages(Set<ScheduleManage> schedulemanages) {
		this.schedulemanages = schedulemanages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partneraccount")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
