package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "servicingportaldb")
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cityId;
	private String cityName;
	private Set<Area> areas = new HashSet<Area>(0);
	private Set<WorkingArea> workingareas = new HashSet<WorkingArea>(0);

	public City() {
	}

	public City(String cityName) {
		this.cityName = cityName;
	}

	public City(String cityName, Set<Area> areas, Set<WorkingArea> workingareas) {
		this.cityName = cityName;
		this.areas = areas;
		this.workingareas = workingareas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CityID", unique = true, nullable = false)
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "CityName", nullable = false, length = 100)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<WorkingArea> getWorkingareas() {
		return this.workingareas;
	}

	public void setWorkingareas(Set<WorkingArea> workingareas) {
		this.workingareas = workingareas;
	}

}
