package com.blackhole.entities;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rolefunction generated by hbm2java
 */
@Entity
@Table(name = "rolefunction", catalog = "servicingportaldb")
public class RoleFunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer roleFuncId;
	private EmployeeAccount employeeaccountByCreateBy;
	private EmployeeAccount employeeaccountByInActiveBy;
	private FunctionProgram functionprogram;
	private Role role;
	private Date createDate;
	private boolean isActive;

	public RoleFunction() {
	}

	public RoleFunction(EmployeeAccount employeeaccountByCreateBy, EmployeeAccount employeeaccountByInActiveBy,
			FunctionProgram functionprogram, Role role, Date createDate, boolean isActive) {
		this.employeeaccountByCreateBy = employeeaccountByCreateBy;
		this.employeeaccountByInActiveBy = employeeaccountByInActiveBy;
		this.functionprogram = functionprogram;
		this.role = role;
		this.createDate = createDate;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RoleFuncID", unique = true, nullable = false)
	public Integer getRoleFuncId() {
		return this.roleFuncId;
	}

	public void setRoleFuncId(Integer roleFuncId) {
		this.roleFuncId = roleFuncId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateBy", nullable = false)
	public EmployeeAccount getEmployeeaccountByCreateBy() {
		return this.employeeaccountByCreateBy;
	}

	public void setEmployeeaccountByCreateBy(EmployeeAccount employeeaccountByCreateBy) {
		this.employeeaccountByCreateBy = employeeaccountByCreateBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InActiveBy", nullable = false)
	public EmployeeAccount getEmployeeaccountByInActiveBy() {
		return this.employeeaccountByInActiveBy;
	}

	public void setEmployeeaccountByInActiveBy(EmployeeAccount employeeaccountByInActiveBy) {
		this.employeeaccountByInActiveBy = employeeaccountByInActiveBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FuncID", nullable = false)
	public FunctionProgram getFunctionprogram() {
		return this.functionprogram;
	}

	public void setFunctionprogram(FunctionProgram functionprogram) {
		this.functionprogram = functionprogram;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleID", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
