package com.servicingportal.entity;
// Generated Mar 1, 2019 9:23:01 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Qna generated by hbm2java
 */
@Entity
@Table(name = "qna", catalog = "servicingportaldb")
public class QnA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer qnAid;
	private EmployeeAccount employeeaccount;
	private QnACatelogy qnacatelogy;
	private String qnAcusEmail;
	private String qnAcontent;
	private Date createDate;
	private String qnAreplyContent;
	private Date qnAreplyDate;
	private boolean qnAisreply;

	public QnA() {
	}

	public QnA(EmployeeAccount employeeaccount, QnACatelogy qnacatelogy, String qnAcusEmail, String qnAcontent,
			Date createDate, boolean qnAisreply) {
		this.employeeaccount = employeeaccount;
		this.qnacatelogy = qnacatelogy;
		this.qnAcusEmail = qnAcusEmail;
		this.qnAcontent = qnAcontent;
		this.createDate = createDate;
		this.qnAisreply = qnAisreply;
	}

	public QnA(EmployeeAccount employeeaccount, QnACatelogy qnacatelogy, String qnAcusEmail, String qnAcontent,
			Date createDate, String qnAreplyContent, Date qnAreplyDate, boolean qnAisreply) {
		this.employeeaccount = employeeaccount;
		this.qnacatelogy = qnacatelogy;
		this.qnAcusEmail = qnAcusEmail;
		this.qnAcontent = qnAcontent;
		this.createDate = createDate;
		this.qnAreplyContent = qnAreplyContent;
		this.qnAreplyDate = qnAreplyDate;
		this.qnAisreply = qnAisreply;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QnAID", unique = true, nullable = false)
	public Integer getQnAid() {
		return this.qnAid;
	}

	public void setQnAid(Integer qnAid) {
		this.qnAid = qnAid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReplyBy", nullable = false)
	public EmployeeAccount getEmployeeaccount() {
		return this.employeeaccount;
	}

	public void setEmployeeaccount(EmployeeAccount employeeaccount) {
		this.employeeaccount = employeeaccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QnACatID", nullable = false)
	public QnACatelogy getQnacatelogy() {
		return this.qnacatelogy;
	}

	public void setQnacatelogy(QnACatelogy qnacatelogy) {
		this.qnacatelogy = qnacatelogy;
	}

	@Column(name = "QnACusEmail", nullable = false, length = 100)
	public String getQnAcusEmail() {
		return this.qnAcusEmail;
	}

	public void setQnAcusEmail(String qnAcusEmail) {
		this.qnAcusEmail = qnAcusEmail;
	}

	@Column(name = "QnAContent", nullable = false, length = 500)
	public String getQnAcontent() {
		return this.qnAcontent;
	}

	public void setQnAcontent(String qnAcontent) {
		this.qnAcontent = qnAcontent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "QnAReplyContent", length = 500)
	public String getQnAreplyContent() {
		return this.qnAreplyContent;
	}

	public void setQnAreplyContent(String qnAreplyContent) {
		this.qnAreplyContent = qnAreplyContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QnAReplyDate", length = 19)
	public Date getQnAreplyDate() {
		return this.qnAreplyDate;
	}

	public void setQnAreplyDate(Date qnAreplyDate) {
		this.qnAreplyDate = qnAreplyDate;
	}

	@Column(name = "QnAISReply", nullable = false)
	public boolean isQnAisreply() {
		return this.qnAisreply;
	}

	public void setQnAisreply(boolean qnAisreply) {
		this.qnAisreply = qnAisreply;
	}

}
